2023-07-29 20:41:45,223 |                  flt |    ERROR | Traceback (most recent call last):
  File "/home/woxel/.local/lib/python3.10/site-packages/foliant/cli/make.py", line 110, in get_config
    config = Parser(project_path, config_file_name, self.logger, quiet).parse()
  File "/home/woxel/.local/lib/python3.10/site-packages/foliant/config/base.py", line 37, in parse
    with open(self.config_path, encoding='utf8') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'foliant.yml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/woxel/.local/lib/python3.10/site-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/home/woxel/.local/lib/python3.10/site-packages/foliant/cli/make.py", line 114, in get_config
    raise FileNotFoundError(f'{exception} not found') from  exception
FileNotFoundError: [Errno 2] No such file or directory: 'foliant.yml' not found

2023-07-29 20:41:45,223 |                  flt | CRITICAL | Config parsing failed.
